ALTER TABLE ai_runs ADD COLUMN input_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_runs ADD COLUMN output_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_runs ADD COLUMN cache_read_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_runs ADD COLUMN cache_creation_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_runs ADD COLUMN tokens_estimated INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_runs ADD COLUMN image_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_runs ADD COLUMN image_size TEXT;
